//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autofac.Extras.DynamicProxy {
    using System;
    using System.Reflection;
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegistrationExtensionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistrationExtensionsResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
#if NET40
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autofac.Extras.DynamicProxy.RegistrationExtensionsResources", typeof(RegistrationExtensionsResources).Assembly);
#else
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autofac.Extras.DynamicProxy.RegistrationExtensionsResources", typeof(RegistrationExtensionsResources).GetTypeInfo().Assembly);
#endif
          resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The transparent proxy does not support the additional interface(s): {0}. 的本地化字符串。
        /// </summary>
        internal static string InterfaceNotSupportedByTransparentProxy {
            get {
                return ResourceManager.GetString("InterfaceNotSupportedByTransparentProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The component {0} cannot use interface interception as it provides services that are not publicly visible interfaces. Check your registration of the component to ensure you&apos;re not enabling interception and registering it as an internal/private interface type. 的本地化字符串。
        /// </summary>
        internal static string InterfaceProxyingOnlySupportsInterfaceServices {
            get {
                return ResourceManager.GetString("InterfaceProxyingOnlySupportsInterfaceServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The transparent proxy of type &apos;{0}&apos; must be an interface. 的本地化字符串。
        /// </summary>
        internal static string TransparentProxyIsNotInterface {
            get {
                return ResourceManager.GetString("TransparentProxyIsNotInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The instance of type &apos;{0}&apos; is not a transparent proxy. 的本地化字符串。
        /// </summary>
        internal static string TypeIsNotTransparentProxy {
            get {
                return ResourceManager.GetString("TypeIsNotTransparentProxy", resourceCulture);
            }
        }
    }
}
