//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autofac.Configuration {
    using System;
  using System.Reflection;
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigurationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
#if NET40
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autofac.Configuration.ConfigurationResources", typeof(ConfigurationResources).Assembly);
#else
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autofac.Configuration.ConfigurationResources", typeof(ConfigurationResources).GetTypeInfo().Assembly);
#endif
          resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} may not be empty. 的本地化字符串。
        /// </summary>
        internal static string ArgumentMayNotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentMayNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key cannot be null or empty in a dictionary parameter. 的本地化字符串。
        /// </summary>
        internal static string DictionaryKeyMayNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("DictionaryKeyMayNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If &apos;name&apos; is specified, &apos;service&apos; must also be specified (component name=&apos;{0}&apos;.) 的本地化字符串。
        /// </summary>
        internal static string ServiceTypeMustBeSpecified {
            get {
                return ResourceManager.GetString("ServiceTypeMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to convert object of type &apos;{0}&apos; to type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string TypeConversionUnsupported {
            get {
                return ResourceManager.GetString("TypeConversionUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; specified in the TypeConverterAttribute is not a TypeConverter. 的本地化字符串。
        /// </summary>
        internal static string TypeConverterAttributeTypeNotConverter {
            get {
                return ResourceManager.GetString("TypeConverterAttributeTypeNotConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; could not be found. It may require assembly qualification, e.g. &quot;MyType, MyAssembly&quot;. 的本地化字符串。
        /// </summary>
        internal static string TypeNotFound {
            get {
                return ResourceManager.GetString("TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value &apos;{0}&apos; is not valid for a Boolean setting. Valid values are &apos;true&apos; and &apos;false&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnrecognisedBoolean {
            get {
                return ResourceManager.GetString("UnrecognisedBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value &apos;{0}&apos; is not valid for the ownership setting. Valid values are &apos;lifetime-scope&apos; (the default) and &apos;external&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnrecognisedOwnership {
            get {
                return ResourceManager.GetString("UnrecognisedOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value &apos;{0}&apos; is not valid for the instance scope setting. Valid values are &apos;single-instance&apos;, &apos;per-dependency&apos; (the default), &apos;per-lifetime-scope&apos;, and &apos;per-request&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnrecognisedScope {
            get {
                return ResourceManager.GetString("UnrecognisedScope", resourceCulture);
            }
        }
    }
}
