//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autofac {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegistrationExtensionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistrationExtensionsResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autofac.RegistrationExtensionsResources", typeof(RegistrationExtensionsResources).AssemblyX());
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The instance  registration &apos;{0}&apos; can support SingleInstance() sharing only. 的本地化字符串。
        /// </summary>
        internal static string InstanceRegistrationsAreSingleInstanceOnly {
            get {
                return ResourceManager.GetString("InstanceRegistrationsAreSingleInstanceOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A metadata attribute of type &apos;{0}&apos; was not found on &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MetadataAttributeNotFound {
            get {
                return ResourceManager.GetString("MetadataAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More than one metadata attribute of type &apos;{0}&apos; was found on &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MultipleMetadataAttributesSameType {
            get {
                return ResourceManager.GetString("MultipleMetadataAttributesSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matching constructor exists on type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string NoMatchingConstructorExists {
            get {
                return ResourceManager.GetString("NoMatchingConstructorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can only attach a registration predicate to a registration that has a callback container attached (e.g., one that was made with a standard ContainerBuilder extension method). 的本地化字符串。
        /// </summary>
        internal static string OnlyIfRequiresCallbackContainer {
            get {
                return ResourceManager.GetString("OnlyIfRequiresCallbackContainer", resourceCulture);
            }
        }
    }
}
