//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySql.Data.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    强类型资源类，用于查找本地化字符串，等等。
    /// </summary>
    // 此类已由 StronglyTypedResourceBuilder 自动生成
    // 通过 ResGen 或 Visual Studio 之类的工具提供的类。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (使用 /str 选项)，或重新生成 VS 项目。
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResourcesX() {
        }
        
        /// <summary>
        ///    返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySql.Data.Properties.ResourcesX", typeof(ResourcesX).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    重写所有项的当前线程的 CurrentUICulture 属性
        ///    使用此强类型资源类进行资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    查找与 Collation with id &apos;{0}&apos; not found. 类似的本地化字符串。
        /// </summary>
        internal static string InvalidCollationId {
            get {
                return ResourceManager.GetString("InvalidCollationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Connection Data is incorrect. 类似的本地化字符串。
        /// </summary>
        internal static string InvalidConnectionData {
            get {
                return ResourceManager.GetString("InvalidConnectionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The connection string is invalid. 类似的本地化字符串。
        /// </summary>
        internal static string InvalidConnectionString {
            get {
                return ResourceManager.GetString("InvalidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 &apos;{0}&apos; is not a valid connection string attribute. 类似的本地化字符串。
        /// </summary>
        internal static string InvalidConnectionStringAttribute {
            get {
                return ResourceManager.GetString("InvalidConnectionStringAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Decimal (BCD) format is invalid. 类似的本地化字符串。
        /// </summary>
        internal static string InvalidDecimalFormat {
            get {
                return ResourceManager.GetString("InvalidDecimalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 {0} is not a valid column name in the row. 类似的本地化字符串。
        /// </summary>
        internal static string InvalidNameIndex {
            get {
                return ResourceManager.GetString("InvalidNameIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 {0} is not a valid index for the row. 类似的本地化字符串。
        /// </summary>
        internal static string InvalidRowIndex {
            get {
                return ResourceManager.GetString("InvalidRowIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Keyword not supported. 类似的本地化字符串。
        /// </summary>
        internal static string KeywordNotSupported {
            get {
                return ResourceManager.GetString("KeywordNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 More than one document id was generated.  Please use the DocumentIds property instead. 类似的本地化字符串。
        /// </summary>
        internal static string MoreThanOneDocumentId {
            get {
                return ResourceManager.GetString("MoreThanOneDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 There is no data at index {0} 类似的本地化字符串。
        /// </summary>
        internal static string NoDataAtIndex {
            get {
                return ResourceManager.GetString("NoDataAtIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 No more data in resultset. 类似的本地化字符串。
        /// </summary>
        internal static string NoMoreData {
            get {
                return ResourceManager.GetString("NoMoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 No placeholders. 类似的本地化字符串。
        /// </summary>
        internal static string NoPlaceholders {
            get {
                return ResourceManager.GetString("NoPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Path not found &apos;{0}&apos;. 类似的本地化字符串。
        /// </summary>
        internal static string PathNotFound {
            get {
                return ResourceManager.GetString("PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Removing a document from a collection requires an _id property. 类似的本地化字符串。
        /// </summary>
        internal static string RemovingRequiresId {
            get {
                return ResourceManager.GetString("RemovingRequiresId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The process of closing the resultset and resulted in results being lost. 类似的本地化字符串。
        /// </summary>
        internal static string ThrowingAwayResults {
            get {
                return ResourceManager.GetString("ThrowingAwayResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Unable to connect to any specified host. 类似的本地化字符串。
        /// </summary>
        internal static string UnableToConnect {
            get {
                return ResourceManager.GetString("UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Unable to read or decode data value. 类似的本地化字符串。
        /// </summary>
        internal static string UnableToDecodeDataValue {
            get {
                return ResourceManager.GetString("UnableToDecodeDataValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Unexpected end of packet found while reading data values 类似的本地化字符串。
        /// </summary>
        internal static string UnexpectedEndOfPacketFound {
            get {
                return ResourceManager.GetString("UnexpectedEndOfPacketFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Unknown placeholder :{0} 类似的本地化字符串。
        /// </summary>
        internal static string UnknownPlaceholder {
            get {
                return ResourceManager.GetString("UnknownPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Value &apos;{0}&apos; is not of the correct type. 类似的本地化字符串。
        /// </summary>
        internal static string ValueNotCorrectType {
            get {
                return ResourceManager.GetString("ValueNotCorrectType", resourceCulture);
            }
        }
    }
}
