//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySql.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesX() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySql.Data.Properties.ResourcesX", typeof(ResourcesX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Collation with id &apos;{0}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string InvalidCollationId {
            get {
                return ResourceManager.GetString("InvalidCollationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection Data is incorrect. 的本地化字符串。
        /// </summary>
        internal static string InvalidConnectionData {
            get {
                return ResourceManager.GetString("InvalidConnectionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The connection string is invalid. 的本地化字符串。
        /// </summary>
        internal static string InvalidConnectionString {
            get {
                return ResourceManager.GetString("InvalidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not a valid connection string attribute. 的本地化字符串。
        /// </summary>
        internal static string InvalidConnectionStringAttribute {
            get {
                return ResourceManager.GetString("InvalidConnectionStringAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decimal (BCD) format is invalid. 的本地化字符串。
        /// </summary>
        internal static string InvalidDecimalFormat {
            get {
                return ResourceManager.GetString("InvalidDecimalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is not a valid column name in the row. 的本地化字符串。
        /// </summary>
        internal static string InvalidNameIndex {
            get {
                return ResourceManager.GetString("InvalidNameIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is not a valid index for the row. 的本地化字符串。
        /// </summary>
        internal static string InvalidRowIndex {
            get {
                return ResourceManager.GetString("InvalidRowIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyword not supported. 的本地化字符串。
        /// </summary>
        internal static string KeywordNotSupported {
            get {
                return ResourceManager.GetString("KeywordNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More than one document id was generated.  Please use the DocumentIds property instead. 的本地化字符串。
        /// </summary>
        internal static string MoreThanOneDocumentId {
            get {
                return ResourceManager.GetString("MoreThanOneDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no data at index {0} 的本地化字符串。
        /// </summary>
        internal static string NoDataAtIndex {
            get {
                return ResourceManager.GetString("NoDataAtIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more data in resultset. 的本地化字符串。
        /// </summary>
        internal static string NoMoreData {
            get {
                return ResourceManager.GetString("NoMoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No placeholders. 的本地化字符串。
        /// </summary>
        internal static string NoPlaceholders {
            get {
                return ResourceManager.GetString("NoPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path not found &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string PathNotFound {
            get {
                return ResourceManager.GetString("PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removing a document from a collection requires an _id property. 的本地化字符串。
        /// </summary>
        internal static string RemovingRequiresId {
            get {
                return ResourceManager.GetString("RemovingRequiresId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The process of closing the resultset and resulted in results being lost. 的本地化字符串。
        /// </summary>
        internal static string ThrowingAwayResults {
            get {
                return ResourceManager.GetString("ThrowingAwayResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to connect to any specified host. 的本地化字符串。
        /// </summary>
        internal static string UnableToConnect {
            get {
                return ResourceManager.GetString("UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to read or decode data value. 的本地化字符串。
        /// </summary>
        internal static string UnableToDecodeDataValue {
            get {
                return ResourceManager.GetString("UnableToDecodeDataValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected end of packet found while reading data values 的本地化字符串。
        /// </summary>
        internal static string UnexpectedEndOfPacketFound {
            get {
                return ResourceManager.GetString("UnexpectedEndOfPacketFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown placeholder :{0} 的本地化字符串。
        /// </summary>
        internal static string UnknownPlaceholder {
            get {
                return ResourceManager.GetString("UnknownPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value &apos;{0}&apos; is not of the correct type. 的本地化字符串。
        /// </summary>
        internal static string ValueNotCorrectType {
            get {
                return ResourceManager.GetString("ValueNotCorrectType", resourceCulture);
            }
        }
    }
}
