//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuteAnt.AsyncEx.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CuteAnt.AsyncEx.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BoundedCapacity must be Unbounded or -1 for this dataflow block. 的本地化字符串。
        /// </summary>
        internal static string Argument_BoundedCapacityNotSupported {
            get {
                return ResourceManager.GetString("Argument_BoundedCapacityNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The argument must be false if no source from which to consume is specified. 的本地化字符串。
        /// </summary>
        internal static string Argument_CantConsumeFromANullSource {
            get {
                return ResourceManager.GetString("Argument_CantConsumeFromANullSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DataflowMessageHeader instance does not represent a valid message header. 的本地化字符串。
        /// </summary>
        internal static string Argument_InvalidMessageHeader {
            get {
                return ResourceManager.GetString("Argument_InvalidMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To construct a DataflowMessageHeader instance, either pass a non-zero value or use the parameterless constructor. 的本地化字符串。
        /// </summary>
        internal static string Argument_InvalidMessageId {
            get {
                return ResourceManager.GetString("Argument_InvalidMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This block must only be used with the source from which it was created. 的本地化字符串。
        /// </summary>
        internal static string Argument_InvalidSourceForFilteredLink {
            get {
                return ResourceManager.GetString("Argument_InvalidSourceForFilteredLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Greedy must be true for this dataflow block. 的本地化字符串。
        /// </summary>
        internal static string Argument_NonGreedyNotSupported {
            get {
                return ResourceManager.GetString("Argument_NonGreedyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number must be no greater than the value specified in BoundedCapacity. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange_BatchSizeMustBeNoGreaterThanBoundedCapacity {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_BatchSizeMustBeNoGreaterThanBoundedCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number must be positive. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange_GenericPositive {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_GenericPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number must be either non-negative and less than or equal to Int32.MaxValue or -1 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange_NeedNonNegOrNegative1 {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedNonNegOrNegative1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object is not a array with the same initialization state as the array to compare it to. 的本地化字符串。
        /// </summary>
        internal static string ArrayInitializedStateNotEqual {
            get {
                return ResourceManager.GetString("ArrayInitializedStateNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object is not a array with the same number of elements as the array to compare it to. 的本地化字符串。
        /// </summary>
        internal static string ArrayLengthsNotEqual {
            get {
                return ResourceManager.GetString("ArrayLengthsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CompleteAdding may not be used concurrently with additions to the collection. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_Add_ConcurrentCompleteAdd {
            get {
                return ResourceManager.GetString("BlockingCollection_Add_ConcurrentCompleteAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The underlying collection didn&apos;t accept the item. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_Add_Failed {
            get {
                return ResourceManager.GetString("BlockingCollection_Add_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At least one of the specified collections is marked as complete with regards to additions. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_CantAddAnyWhenCompleted {
            get {
                return ResourceManager.GetString("BlockingCollection_CantAddAnyWhenCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All collections are marked as complete with regards to additions. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_CantTakeAnyWhenAllDone {
            get {
                return ResourceManager.GetString("BlockingCollection_CantTakeAnyWhenAllDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collection argument is empty and has been marked as complete with regards to additions. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_CantTakeWhenDone {
            get {
                return ResourceManager.GetString("BlockingCollection_CantTakeWhenDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collection has been marked as complete with regards to additions. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_Completed {
            get {
                return ResourceManager.GetString("BlockingCollection_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The array argument is of the incorrect type. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_CopyTo_IncorrectType {
            get {
                return ResourceManager.GetString("BlockingCollection_CopyTo_IncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The array argument is multidimensional. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_CopyTo_MultiDim {
            get {
                return ResourceManager.GetString("BlockingCollection_CopyTo_MultiDim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The index argument must be greater than or equal zero. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_CopyTo_NonNegative {
            get {
                return ResourceManager.GetString("BlockingCollection_CopyTo_NonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of elements in the collection is greater than the available space from index to the end of the destination array. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_CopyTo_TooManyElems {
            get {
                return ResourceManager.GetString("BlockingCollection_CopyTo_TooManyElems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The boundedCapacity argument must be positive. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_ctor_BoundedCapacityRange {
            get {
                return ResourceManager.GetString("BlockingCollection_ctor_BoundedCapacityRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collection argument contains more items than are allowed by the boundedCapacity. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_ctor_CountMoreThanCapacity {
            get {
                return ResourceManager.GetString("BlockingCollection_ctor_CountMoreThanCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collection has been disposed. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_Disposed {
            get {
                return ResourceManager.GetString("BlockingCollection_Disposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The underlying collection was modified from outside of the BlockingCollection&lt;T&gt;. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_Take_CollectionModified {
            get {
                return ResourceManager.GetString("BlockingCollection_Take_CollectionModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified timeout must represent a value between -1 and {0}, inclusive. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_TimeoutInvalid {
            get {
                return ResourceManager.GetString("BlockingCollection_TimeoutInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collections argument contains at least one disposed element. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_ValidateCollectionsArray_DispElems {
            get {
                return ResourceManager.GetString("BlockingCollection_ValidateCollectionsArray_DispElems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collections length is greater than the supported range for 32 bit machine. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_ValidateCollectionsArray_LargeSize {
            get {
                return ResourceManager.GetString("BlockingCollection_ValidateCollectionsArray_LargeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collections argument contains at least one null element. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_ValidateCollectionsArray_NullElems {
            get {
                return ResourceManager.GetString("BlockingCollection_ValidateCollectionsArray_NullElems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collections argument is a zero-length array. 的本地化字符串。
        /// </summary>
        internal static string BlockingCollection_ValidateCollectionsArray_ZeroSize {
            get {
                return ResourceManager.GetString("BlockingCollection_ValidateCollectionsArray_ZeroSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find the old value 的本地化字符串。
        /// </summary>
        internal static string CannotFindOldValue {
            get {
                return ResourceManager.GetString("CannotFindOldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capacity was less than the current Count of elements. 的本地化字符串。
        /// </summary>
        internal static string CapacityMustBeGreaterThanOrEqualToCount {
            get {
                return ResourceManager.GetString("CapacityMustBeGreaterThanOrEqualToCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MoveToImmutable can only be performed when Count equals Capacity. 的本地化字符串。
        /// </summary>
        internal static string CapacityMustEqualCountOnMove {
            get {
                return ResourceManager.GetString("CapacityMustEqualCountOnMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection was modified; enumeration operation may not execute. 的本地化字符串。
        /// </summary>
        internal static string CollectionModifiedDuringEnumeration {
            get {
                return ResourceManager.GetString("CollectionModifiedDuringEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The operation was canceled. 的本地化字符串。
        /// </summary>
        internal static string Common_OperationCanceled {
            get {
                return ResourceManager.GetString("Common_OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The array argument is null. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentBag_CopyTo_ArgumentNullException {
            get {
                return ResourceManager.GetString("ConcurrentBag_CopyTo_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The index argument must be greater than or equal zero. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentBag_CopyTo_ArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("ConcurrentBag_CopyTo_ArgumentOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collection argument is null. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentBag_Ctor_ArgumentNullException {
            get {
                return ResourceManager.GetString("ConcurrentBag_Ctor_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The SyncRoot property may not be used for the synchronization of concurrent collections. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentCollection_SyncRoot_NotSupported {
            get {
                return ResourceManager.GetString("ConcurrentCollection_SyncRoot_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The SyncRoot property may not be used for the synchronization of concurrent collections. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentCollection_SyncRoot_NotSupported1 {
            get {
                return ResourceManager.GetString("ConcurrentCollection_SyncRoot_NotSupported1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The array is multidimensional, or the type parameter for the set cannot be cast automatically to the type of the destination array. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentDictionary_ArrayIncorrectType {
            get {
                return ResourceManager.GetString("ConcurrentDictionary_ArrayIncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentDictionary_ArrayNotLargeEnough {
            get {
                return ResourceManager.GetString("ConcurrentDictionary_ArrayNotLargeEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The capacity argument must be greater than or equal to zero. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentDictionary_CapacityMustNotBeNegative {
            get {
                return ResourceManager.GetString("ConcurrentDictionary_CapacityMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The concurrencyLevel argument must be positive. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentDictionary_ConcurrencyLevelMustBePositive {
            get {
                return ResourceManager.GetString("ConcurrentDictionary_ConcurrencyLevelMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The index argument is less than zero. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentDictionary_IndexIsNegative {
            get {
                return ResourceManager.GetString("ConcurrentDictionary_IndexIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TKey is a reference type and item.Key is null. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentDictionary_ItemKeyIsNull {
            get {
                return ResourceManager.GetString("ConcurrentDictionary_ItemKeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The key already existed in the dictionary. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentDictionary_KeyAlreadyExisted {
            get {
                return ResourceManager.GetString("ConcurrentDictionary_KeyAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The source argument contains duplicate keys. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentDictionary_SourceContainsDuplicateKeys {
            get {
                return ResourceManager.GetString("ConcurrentDictionary_SourceContainsDuplicateKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The key was of an incorrect type for this dictionary. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentDictionary_TypeOfKeyIncorrect {
            get {
                return ResourceManager.GetString("ConcurrentDictionary_TypeOfKeyIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value was of an incorrect type for this dictionary. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentDictionary_TypeOfValueIncorrect {
            get {
                return ResourceManager.GetString("ConcurrentDictionary_TypeOfValueIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The count argument must be greater than or equal to zero. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentStack_PushPopRange_CountOutOfRange {
            get {
                return ResourceManager.GetString("ConcurrentStack_PushPopRange_CountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The sum of the startIndex and count arguments must be less than or equal to the collection&apos;s Count. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentStack_PushPopRange_InvalidCount {
            get {
                return ResourceManager.GetString("ConcurrentStack_PushPopRange_InvalidCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The startIndex argument must be greater than or equal to zero. 的本地化字符串。
        /// </summary>
        internal static string ConcurrentStack_PushPopRange_StartOutOfRange {
            get {
                return ResourceManager.GetString("ConcurrentStack_PushPopRange_StartOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An element with the same key but a different value already exists. Key: {0} 的本地化字符串。
        /// </summary>
        internal static string DuplicateKey {
            get {
                return ResourceManager.GetString("DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block {0} completed as {1}. {2} 的本地化字符串。
        /// </summary>
        internal static string event_DataflowBlockCompleted {
            get {
                return ResourceManager.GetString("event_DataflowBlockCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block of type {0} instantiated with Id {1}. 的本地化字符串。
        /// </summary>
        internal static string event_DataflowBlockCreated {
            get {
                return ResourceManager.GetString("event_DataflowBlockCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source {0} linked to target {1}. 的本地化字符串。
        /// </summary>
        internal static string event_DataflowBlockLinking {
            get {
                return ResourceManager.GetString("event_DataflowBlockLinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source {0} unlinked from target {1}. 的本地化字符串。
        /// </summary>
        internal static string event_DataflowBlockUnlinking {
            get {
                return ResourceManager.GetString("event_DataflowBlockUnlinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1} task launched from block {0} with {2} message(s) pending. 的本地化字符串。
        /// </summary>
        internal static string event_TaskLaunchedForMessageHandling {
            get {
                return ResourceManager.GetString("event_TaskLaunchedForMessageHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation does not apply to an empty instance. 的本地化字符串。
        /// </summary>
        internal static string InvalidEmptyOperation {
            get {
                return ResourceManager.GetString("InvalidEmptyOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The source completed without providing data to receive. 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_DataNotAvailableForReceive {
            get {
                return ResourceManager.GetString("InvalidOperation_DataNotAvailableForReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target block failed to consume a message it had successfully reserved. 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_FailedToConsumeReservedMessage {
            get {
                return ResourceManager.GetString("InvalidOperation_FailedToConsumeReservedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target does not have the message reserved. 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_MessageNotReservedByTarget {
            get {
                return ResourceManager.GetString("InvalidOperation_MessageNotReservedByTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation cannot be performed on a default instance of ImmutableArray&lt;T&gt;.  Consider initializing the array, or checking the ImmutableArray&lt;T&gt;.IsDefault property. 的本地化字符串。
        /// </summary>
        internal static string InvalidOperationOnDefaultArray {
            get {
                return ResourceManager.GetString("InvalidOperationOnDefaultArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This member is not supported on this dataflow block. The block is intended for a specific purpose that does not utilize this member. 的本地化字符串。
        /// </summary>
        internal static string NotSupported_MemberNotNeeded {
            get {
                return ResourceManager.GetString("NotSupported_MemberNotNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Partitioner source returned a null enumerator. 的本地化字符串。
        /// </summary>
        internal static string Parallel_ForEach_NullEnumerator {
            get {
                return ResourceManager.GetString("Parallel_ForEach_NullEnumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This method requires the use of an OrderedPartitioner with the KeysNormalized property set to true. 的本地化字符串。
        /// </summary>
        internal static string Parallel_ForEach_OrderedPartitionerKeysNotNormalized {
            get {
                return ResourceManager.GetString("Parallel_ForEach_OrderedPartitionerKeysNotNormalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Partitioner used here must support dynamic partitioning. 的本地化字符串。
        /// </summary>
        internal static string Parallel_ForEach_PartitionerNotDynamic {
            get {
                return ResourceManager.GetString("Parallel_ForEach_PartitionerNotDynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Partitioner used here returned a null partitioner source. 的本地化字符串。
        /// </summary>
        internal static string Parallel_ForEach_PartitionerReturnedNull {
            get {
                return ResourceManager.GetString("Parallel_ForEach_PartitionerReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One of the actions was null. 的本地化字符串。
        /// </summary>
        internal static string Parallel_Invoke_ActionNull {
            get {
                return ResourceManager.GetString("Parallel_Invoke_ActionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Break was called after Stop was called. 的本地化字符串。
        /// </summary>
        internal static string ParallelState_Break_InvalidOperationException_BreakAfterStop {
            get {
                return ResourceManager.GetString("ParallelState_Break_InvalidOperationException_BreakAfterStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This method is not supported. 的本地化字符串。
        /// </summary>
        internal static string ParallelState_NotSupportedException_UnsupportedMethod {
            get {
                return ResourceManager.GetString("ParallelState_NotSupportedException_UnsupportedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop was called after Break was called. 的本地化字符串。
        /// </summary>
        internal static string ParallelState_Stop_InvalidOperationException_StopAfterBreak {
            get {
                return ResourceManager.GetString("ParallelState_Stop_InvalidOperationException_StopAfterBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dynamic partitions are not supported by this partitioner. 的本地化字符串。
        /// </summary>
        internal static string Partitioner_DynamicPartitionsNotSupported {
            get {
                return ResourceManager.GetString("Partitioner_DynamicPartitionsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not call GetEnumerator on partitions after the source enumerable is disposed 的本地化字符串。
        /// </summary>
        internal static string PartitionerStatic_CanNotCallGetEnumeratorAfterSourceHasBeenDisposed {
            get {
                return ResourceManager.GetString("PartitionerStatic_CanNotCallGetEnumeratorAfterSourceHasBeenDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MoveNext must be called at least once before calling Current. 的本地化字符串。
        /// </summary>
        internal static string PartitionerStatic_CurrentCalledBeforeMoveNext {
            get {
                return ResourceManager.GetString("PartitionerStatic_CurrentCalledBeforeMoveNext", resourceCulture);
            }
        }
    }
}
