//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuteAnt.Internal {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CuteAnt.Internal.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Count must be positive and count must refer to a location within the collection. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange_Count {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index was out of range. Must be non-negative and less than the size of the collection. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange_Index {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-negative number required. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange_NeedNonNegNum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedNonNegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capacity may not be negative. 的本地化字符串。
        /// </summary>
        internal static string Capacity_May_Not_Be_Negative {
            get {
                return ResourceManager.GetString("Capacity_May_Not_Be_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destination array cannot be null. 的本地化字符串。
        /// </summary>
        internal static string Dest_Array_Cannot_Be_Null {
            get {
                return ResourceManager.GetString("Dest_Array_Cannot_Be_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashes are in the wrong position for GUID parsing. 的本地化字符串。
        /// </summary>
        internal static string Format_GuidDashes {
            get {
                return ResourceManager.GetString("Format_GuidDashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guid string should only contain hexadecimal characters. 的本地化字符串。
        /// </summary>
        internal static string Format_GuidInvalidChar {
            get {
                return ResourceManager.GetString("Format_GuidInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx). 的本地化字符串。
        /// </summary>
        internal static string Format_GuidInvLen {
            get {
                return ResourceManager.GetString("Format_GuidInvLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized Guid format. 的本地化字符串。
        /// </summary>
        internal static string Format_GuidUnrecognized {
            get {
                return ResourceManager.GetString("Format_GuidUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format string can be only &quot;D&quot;, &quot;d&quot;, &quot;N&quot;, &quot;n&quot;, &quot;P&quot;, &quot;p&quot;, &quot;B&quot;, &quot;b&quot;, &quot;X&quot; or &quot;x&quot;. 的本地化字符串。
        /// </summary>
        internal static string Format_InvalidGuidFormatSpecification {
            get {
                return ResourceManager.GetString("Format_InvalidGuidFormatSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arrays not initialized properly 的本地化字符串。
        /// </summary>
        internal static string ImmutableArray_Arrays_Not_Initialized {
            get {
                return ResourceManager.GetString("ImmutableArray_Arrays_Not_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other is not an array of T 的本地化字符串。
        /// </summary>
        internal static string ImmutableArray_Not_Array {
            get {
                return ResourceManager.GetString("ImmutableArray_Not_Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must provide at least one type to test against 的本地化字符串。
        /// </summary>
        internal static string Provide_At_Least_One_Type {
            get {
                return ResourceManager.GetString("Provide_At_Least_One_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A type name must not be null nor consist of only whitespace. 的本地化字符串。
        /// </summary>
        internal static string Type_Name_Must_Not_Null {
            get {
                return ResourceManager.GetString("Type_Name_Must_Not_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value cannot be null. 的本地化字符串。
        /// </summary>
        internal static string Value_Cannot_Be_Null {
            get {
                return ResourceManager.GetString("Value_Cannot_Be_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value is of incorrect type. 的本地化字符串。
        /// </summary>
        internal static string Value_Is_Of_Incorrect_Type {
            get {
                return ResourceManager.GetString("Value_Is_Of_Incorrect_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 value must not be null 的本地化字符串。
        /// </summary>
        internal static string Value_Must_Not_Be_Null {
            get {
                return ResourceManager.GetString("Value_Must_Not_Be_Null", resourceCulture);
            }
        }
    }
}
