//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuteAnt.AsyncEx.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    强类型资源类，用于查找本地化字符串，等等。
    /// </summary>
    // 此类已由 StronglyTypedResourceBuilder 自动生成
    // 通过 ResGen 或 Visual Studio 之类的工具提供的类。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (使用 /str 选项)，或重新生成 VS 项目。
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Errors() {
        }
        
        /// <summary>
        ///    返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CuteAnt.AsyncEx.Properties.Errors", typeof(Errors).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    重写所有项的当前线程的 CurrentUICulture 属性
        ///    使用此强类型资源类进行资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    查找与 Individual cursor branches cannot be reset.  To reset the entire cursor, call Reset on the primary cursor object instead. 类似的本地化字符串。
        /// </summary>
        internal static string CannotResetCursorBranch {
            get {
                return ResourceManager.GetString("CannotResetCursorBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The specified DependencyProperty was not found on the specified DependencyObject. 类似的本地化字符串。
        /// </summary>
        internal static string DependencyPropertyNotFound {
            get {
                return ResourceManager.GetString("DependencyPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The event member&apos;s delegate has an arguments parameter that is not compatible with System.EventArgs.  Member name: {0}. 类似的本地化字符串。
        /// </summary>
        internal static string EventIsNotCompatibleWithEventArgs {
            get {
                return ResourceManager.GetString("EventIsNotCompatibleWithEventArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The event member&apos;s delegate is not compatible with System.EventHandler&lt;TEventArgs&gt;.  Member name: {0}. 类似的本地化字符串。
        /// </summary>
        internal static string EventIsNotCompatibleWithEventHandler {
            get {
                return ResourceManager.GetString("EventIsNotCompatibleWithEventHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 An in-line query cannot be parsed while the grammar is being defined. 类似的本地化字符串。
        /// </summary>
        internal static string InlineParseNotSupported {
            get {
                return ResourceManager.GetString("InlineParseNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The temporary in-line parser does not have a grammar. 类似的本地化字符串。
        /// </summary>
        internal static string InlineParserWithoutGrammar {
            get {
                return ResourceManager.GetString("InlineParserWithoutGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The format of the specified directory path is invalid. 类似的本地化字符串。
        /// </summary>
        internal static string InvalidFormatDirectoryPath {
            get {
                return ResourceManager.GetString("InvalidFormatDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The PairDirection value is invalid. 类似的本地化字符串。
        /// </summary>
        internal static string InvalidPairDirectionValue {
            get {
                return ResourceManager.GetString("InvalidPairDirectionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Parse cannot be called again until the current parse operation completes. 类似的本地化字符串。
        /// </summary>
        internal static string ParseCalledWhileParsing {
            get {
                return ResourceManager.GetString("ParseCalledWhileParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Syntax error in parser input sequence. 类似的本地化字符串。
        /// </summary>
        internal static string ParseExceptionMessage {
            get {
                return ResourceManager.GetString("ParseExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 {0}{1}Source index: {2}. 类似的本地化字符串。
        /// </summary>
        internal static string ParseExceptionMessageOverrideFormat {
            get {
                return ResourceManager.GetString("ParseExceptionMessageOverrideFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The operation is unavailable until after Parse has been called and it has completed successfully. 类似的本地化字符串。
        /// </summary>
        internal static string ParseNotCalledOrFailed {
            get {
                return ResourceManager.GetString("ParseNotCalledOrFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The parser cannot move the cursor to the end of the input sequence because the current index is ahead of the latest index. 类似的本地化字符串。
        /// </summary>
        internal static string ParserCannotMoveToEndBackward {
            get {
                return ResourceManager.GetString("ParserCannotMoveToEndBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The Next property cannot be read until after Parse is called. 类似的本地化字符串。
        /// </summary>
        internal static string ParserNextNotReady {
            get {
                return ResourceManager.GetString("ParserNextNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The parser does not allow new subscriptions until the current parse operation completes. 类似的本地化字符串。
        /// </summary>
        internal static string ParseSubscribeCalledWhileParsing {
            get {
                return ResourceManager.GetString("ParseSubscribeCalledWhileParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The specified property does not support change events. 类似的本地化字符串。
        /// </summary>
        internal static string PropertyDoesNotSupportChangeEvents {
            get {
                return ResourceManager.GetString("PropertyDoesNotSupportChangeEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The specified expression contains an indexer. 类似的本地化字符串。
        /// </summary>
        internal static string PropertyExpressionContainsIndexer {
            get {
                return ResourceManager.GetString("PropertyExpressionContainsIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The specified expression cannot be understood as a property. 类似的本地化字符串。
        /// </summary>
        internal static string PropertyExpressionNotUnderstood {
            get {
                return ResourceManager.GetString("PropertyExpressionNotUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The specified expression cannot be understood as a property being read from a local variable, field, another property, or a chain of fields and properties. 类似的本地化字符串。
        /// </summary>
        internal static string PropertyExpressionOwnerNotUnderstood {
            get {
                return ResourceManager.GetString("PropertyExpressionOwnerNotUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The specified expression contains more than just fields and properties. 类似的本地化字符串。
        /// </summary>
        internal static string PropertyExpressionTooComplex {
            get {
                return ResourceManager.GetString("PropertyExpressionTooComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The owner of the specified property could not be determined. 类似的本地化字符串。
        /// </summary>
        internal static string PropertyExpresssionOwnerNotDetermined {
            get {
                return ResourceManager.GetString("PropertyExpresssionOwnerNotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The specified property is read-only.  Property name: {0}. 类似的本地化字符串。
        /// </summary>
        internal static string PropertyIsReadOnly {
            get {
                return ResourceManager.GetString("PropertyIsReadOnly", resourceCulture);
            }
        }
    }
}
