//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuteAnt.AsyncEx.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    强类型资源类，用于查找本地化字符串，等等。
    /// </summary>
    // 此类已由 StronglyTypedResourceBuilder 自动生成
    // 通过 ResGen 或 Visual Studio 之类的工具提供的类。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (使用 /str 选项)，或重新生成 VS 项目。
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Text() {
        }
        
        /// <summary>
        ///    返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CuteAnt.AsyncEx.Properties.Text", typeof(Text).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    重写所有项的当前线程的 CurrentUICulture 属性
        ///    使用此强类型资源类进行资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    查找与 Disposed subscription. 类似的本地化字符串。
        /// </summary>
        internal static string DefaultDisposedSubscriptionMessage {
            get {
                return ResourceManager.GetString("DefaultDisposedSubscriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Disposing subscription. 类似的本地化字符串。
        /// </summary>
        internal static string DefaultDisposingSubscriptionMessage {
            get {
                return ResourceManager.GetString("DefaultDisposingSubscriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Sequence completed. 类似的本地化字符串。
        /// </summary>
        internal static string DefaultOnCompletedMessage {
            get {
                return ResourceManager.GetString("DefaultOnCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Subscribed to observable. 类似的本地化字符串。
        /// </summary>
        internal static string DefaultSubscribedMessage {
            get {
                return ResourceManager.GetString("DefaultSubscribedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Subscribing to observable. 类似的本地化字符串。
        /// </summary>
        internal static string DefaultSubscribingMessage {
            get {
                return ResourceManager.GetString("DefaultSubscribingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Disposed subscription: {0}. 类似的本地化字符串。
        /// </summary>
        internal static string DisposedSubscriptionFormat {
            get {
                return ResourceManager.GetString("DisposedSubscriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Disposing subscription: {0}. 类似的本地化字符串。
        /// </summary>
        internal static string DisposingSubscriptionFormat {
            get {
                return ResourceManager.GetString("DisposingSubscriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Increasing FileSystemWatcher buffer size from {0} to {1}. 类似的本地化字符串。
        /// </summary>
        internal static string FileSystemWatcherBufferChangeFormat {
            get {
                return ResourceManager.GetString("FileSystemWatcherBufferChangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 FileSystemWatcher buffer overflow: {0} 类似的本地化字符串。
        /// </summary>
        internal static string FileSystemWatcherBufferOverflowFormat {
            get {
                return ResourceManager.GetString("FileSystemWatcherBufferOverflowFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Subscribed to observable: {0}. 类似的本地化字符串。
        /// </summary>
        internal static string SubscribedFormat {
            get {
                return ResourceManager.GetString("SubscribedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Subscribing to observable: {0}. 类似的本地化字符串。
        /// </summary>
        internal static string SubscribingFormat {
            get {
                return ResourceManager.GetString("SubscribingFormat", resourceCulture);
            }
        }
    }
}
