//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuteAnt.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    强类型资源类，用于查找本地化字符串，等等。
    /// </summary>
    // 此类已由 StronglyTypedResourceBuilder 自动生成
    // 通过 ResGen 或 Visual Studio 之类的工具提供的类。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (使用 /str 选项)，或重新生成 VS 项目。
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CuteAnt.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    重写所有项的当前线程的 CurrentUICulture 属性
        ///    使用此强类型资源类进行资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    查找与 This transform has already transformed its final block and can no longer transform additional data. 类似的本地化字符串。
        /// </summary>
        internal static string AlreadyTransformedFinalBlock {
            get {
                return ResourceManager.GetString("AlreadyTransformedFinalBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Cannot decrypt a partial block. 类似的本地化字符串。
        /// </summary>
        internal static string CannotDecryptPartialBlock {
            get {
                return ResourceManager.GetString("CannotDecryptPartialBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 {0} [ 线程 {1} ]{2} 类似的本地化字符串。
        /// </summary>
        internal static string ChildThreadName {
            get {
                return ResourceManager.GetString("ChildThreadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与     Cpu 时钟周期 :    {0} 纳秒 类似的本地化字符串。
        /// </summary>
        internal static string CPUCycles {
            get {
                return ResourceManager.GetString("CPUCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与     GC 代数 {0}    :    {1} 类似的本地化字符串。
        /// </summary>
        internal static string CPUGen {
            get {
                return ResourceManager.GetString("CPUGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Alias &apos;{0}&apos; already exists in the CryptoConfig2 map. 类似的本地化字符串。
        /// </summary>
        internal static string DuplicateCryptoConfigAlias {
            get {
                return ResourceManager.GetString("DuplicateCryptoConfigAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Null or empty CryptoConfig aliases are invalid. 类似的本地化字符串。
        /// </summary>
        internal static string EmptyCryptoConfigAlias {
            get {
                return ResourceManager.GetString("EmptyCryptoConfigAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与     执行失败计数 :    {0} 类似的本地化字符串。
        /// </summary>
        internal static string ExecuteFailureCount {
            get {
                return ResourceManager.GetString("ExecuteFailureCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与     执行成功计数 :    {0} 类似的本地化字符串。
        /// </summary>
        internal static string ExecuteSuccessCount {
            get {
                return ResourceManager.GetString("ExecuteSuccessCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 CNG chaining modes cannot have empty names. 类似的本地化字符串。
        /// </summary>
        internal static string InvalidChainingModeName {
            get {
                return ResourceManager.GetString("InvalidChainingModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The specified IV was not long enough. IVs must be the same length as the block size. 类似的本地化字符串。
        /// </summary>
        internal static string InvalidIVSize {
            get {
                return ResourceManager.GetString("InvalidIVSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The padding on the block is invalid and cannot be removed. 类似的本地化字符串。
        /// </summary>
        internal static string InvalidPadding {
            get {
                return ResourceManager.GetString("InvalidPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The specified RSA parameters are not valid; both Exponent and Modulus are required fields. 类似的本地化字符串。
        /// </summary>
        internal static string InvalidRsaParameters {
            get {
                return ResourceManager.GetString("InvalidRsaParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The hash algorithm is not supported for signatures. Only MD5, SHA1, SHA256,SHA384, and SHA512 are supported at this time. 类似的本地化字符串。
        /// </summary>
        internal static string InvalidSignatureHashAlgorithm {
            get {
                return ResourceManager.GetString("InvalidSignatureHashAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The specified tag is not a valid size for this implementation. 类似的本地化字符串。
        /// </summary>
        internal static string InvalidTagSize {
            get {
                return ResourceManager.GetString("InvalidTagSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与     循环次数 : {0} 类似的本地化字符串。
        /// </summary>
        internal static string IterationCount {
            get {
                return ResourceManager.GetString("IterationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The specified key must be an RSA key 类似的本地化字符串。
        /// </summary>
        internal static string KeyMustBeRsa {
            get {
                return ResourceManager.GetString("KeyMustBeRsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 必须大于 0. 类似的本地化字符串。
        /// </summary>
        internal static string MessageThan0 {
            get {
                return ResourceManager.GetString("MessageThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 No IV was given, and the specified CipherMode requires the use of an IV. 类似的本地化字符串。
        /// </summary>
        internal static string MissingIV {
            get {
                return ResourceManager.GetString("MissingIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与  模拟思考时间 : {0} 类似的本地化字符串。
        /// </summary>
        internal static string MockThinkTime {
            get {
                return ResourceManager.GetString("MockThinkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 {0} [多线程并发]{1} 类似的本地化字符串。
        /// </summary>
        internal static string MultiThreadName {
            get {
                return ResourceManager.GetString("MultiThreadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与  =&gt; 类似的本地化字符串。
        /// </summary>
        internal static string NameSuffix {
            get {
                return ResourceManager.GetString("NameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 {0} [单线程]{1} 类似的本地化字符串。
        /// </summary>
        internal static string SingleThreadName {
            get {
                return ResourceManager.GetString("SingleThreadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Authentication tags are only available after the final block has been transformed. 类似的本地化字符串。
        /// </summary>
        internal static string TagIsOnlyGeneratedAfterFinalBlock {
            get {
                return ResourceManager.GetString("TagIsOnlyGeneratedAfterFinalBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Authentication tags are only generated during encryption operations, and cannot be retrieved from a decryption transform. 类似的本地化字符串。
        /// </summary>
        internal static string TagIsOnlyGeneratedDuringEncryption {
            get {
                return ResourceManager.GetString("TagIsOnlyGeneratedDuringEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与  线程计数 : {0} 类似的本地化字符串。
        /// </summary>
        internal static string ThreadCount {
            get {
                return ResourceManager.GetString("ThreadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与     运行时间     :    {0} 毫秒 类似的本地化字符串。
        /// </summary>
        internal static string TimeElapsed {
            get {
                return ResourceManager.GetString("TimeElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The specified CipherMode is not supported with BCrypt symmetric algorithms. 类似的本地化字符串。
        /// </summary>
        internal static string UnsupportedCipherMode {
            get {
                return ResourceManager.GetString("UnsupportedCipherMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The specified PaddingMode is not supported 类似的本地化字符串。
        /// </summary>
        internal static string UnsupportedPaddingMode {
            get {
                return ResourceManager.GetString("UnsupportedPaddingMode", resourceCulture);
            }
        }
    }
}
