//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuteAnt.Runtime.Internal {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CuteAnt.Runtime.Internal.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Surrogates Not Allowed As Single Char 的本地化字符串。
        /// </summary>
        internal static string Arg_SurrogatesNotAllowedAsSingleChar {
            get {
                return ResourceManager.GetString("Arg_SurrogatesNotAllowedAsSingleChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection. 的本地化字符串。
        /// </summary>
        internal static string Argument_InvalidOffLen {
            get {
                return ResourceManager.GetString("Argument_InvalidOffLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-negative number required. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange_NeedNonNegNum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedNonNegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buffer Is Not Right Size For Buffer Manager 的本地化字符串。
        /// </summary>
        internal static string BufferIsNotRightSizeForBufferManager {
            get {
                return ResourceManager.GetString("BufferIsNotRightSizeForBufferManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lambda filter requires at least one non-null parameter to be functional 的本地化字符串。
        /// </summary>
        internal static string Lambda_Filter_Requires {
            get {
                return ResourceManager.GetString("Lambda_Filter_Requires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot write to a closed TextWriter. 的本地化字符串。
        /// </summary>
        internal static string ObjectDisposed_WriterClosed {
            get {
                return ResourceManager.GetString("ObjectDisposed_WriterClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset points before the start of the stream. 的本地化字符串。
        /// </summary>
        internal static string Offset_Before_Start_Stream {
            get {
                return ResourceManager.GetString("Offset_Before_Start_Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset points beyond the end of the stream. 的本地化字符串。
        /// </summary>
        internal static string Offset_Beyond_End_Stream {
            get {
                return ResourceManager.GetString("Offset_Beyond_End_Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of segments must be greater than zero. 的本地化字符串。
        /// </summary>
        internal static string Segments_NeedNonNegNum {
            get {
                return ResourceManager.GetString("Segments_NeedNonNegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of this argument must be non-negative. 的本地化字符串。
        /// </summary>
        internal static string ValueMustBeNonNegative {
            get {
                return ResourceManager.GetString("ValueMustBeNonNegative", resourceCulture);
            }
        }
    }
}
